### PR TITLE
Metasploit::Cache::Payload::Single::Instance

### PR DESCRIPTION
**Pull request by limhoff-r7**
MSP-12424

# Pre-verification Steps
- [x] Merge #25

# Verification Steps
- [x] `rm Gemfile.lock`
- [ ] `bundle install`

## Feature tests
- [x] `open docs/images/metasploit-cache.png`
- [ ] VERIFY all attribute columns for Metasploit::Cache::Payload::Single::Instance are implemented
- [x] VERIFY payload_single_class_id column is implemented as are the payload_single_class association
- [ ] VERIFY inverse payload_single_instance association on Metasploit::Cache::Payload::Single::Class.

## Test coverage
- [ ] `rake cucumber spec coverage`
- [ ] VERIFY no failures
- [ ] VERIFY 100% coverage

## Documentation
- [ ] `rake yard`
- [ ] VERIFY only warnings are:
```
[warn]: @param tag has unknown parameter name: module_instances 
    in file `app/models/metasploit/cache/module/class.rb' near line 147
[warn]: @param tag has unknown parameter name: module_instance 
    in file `app/models/metasploit/cache/module/instance.rb' near line 317
[warn]: @param tag has unknown parameter name: architecture_abbreviations 
    in file `app/models/metasploit/cache/module/instance.rb' near line 336
[warn]: @param tag has unknown parameter name: architectured 
    in file `app/models/metasploit/cache/module/instance.rb' near line 353
[warn]: @param tag has unknown parameter name: platforms 
    in file `app/models/metasploit/cache/module/instance.rb' near line 367
[warn]: @param tag has unknown parameter name: platform_fully_qualified_names 
    in file `app/models/metasploit/cache/module/instance.rb' near line 403
[warn]: @param tag has unknown parameter name: module_target 
    in file `app/models/metasploit/cache/module/instance.rb' near line 420
[warn]: @param tag has unknown parameter name: module_instance 
    in file `app/models/metasploit/cache/module/instance.rb' near line 434
[warn]: @param tag has unknown parameter name: module_target 
    in file `app/models/metasploit/cache/module/instance.rb' near line 492
```
- [ ] VERIFY no undocumented objects

# Post-merge Steps

Perform these steps prior to pushing to master or the build will be broken on master.

## Version
- [ ] Edit `lib/metasploit/cache/version.rb`
- [ ] Remove `PRERELEASE` and its comment as `PRERELEASE` is not defined on master.

## Gem build
- [ ] gem build *.gemspec
- [ ] VERIFY the gem has no '.pre' version suffix.

## RSpec
- [ ] `rake spec`
- [ ] VERIFY version examples pass without failures

## Commit & Push
- [ ] `git commit -a`
- [ ] `git push origin master`

### CODE REVIEW

**Comment by jlee-r7** [comment]
I'm seeing hundreds of local failures.  Rebuilding after `db:drop`

**Comment by jlee-r7** [comment]
misfire, that was for #35

**Comment by trosen-r7** [comment]
handler_id column is missing, but is referenced in the ERD. no association exists for handler either.

**Comment by limhoff-r7** [comment]
handler_id is expected not to be implemented until #41

**Pull request merged**
